tasks:
  ssh_login_monitor:
    name: "SSH Login Monitoring"
    description: "Detect suspicious login attempts."
    
    # Task type: one-shot, cron, daemon, or on-demand
    task_type: cron      # one-shot, cron, daemon, on-demand
    schedule: "*/1 * * * *"  # only for cron tasks: standard cron syntax
    continuous: false        # optional flag for daemon-like tasks

    dependencies:
      inputs:
        - /var/log/auth.log
        - journalctl -u sshd
      commands:
        - journalctl
        - grep
      libraries:
        - python-systemd
      permissions: root
      runtime:
        disk_min_mb: 100
        time_sync: true

    steps:
      - collect_logs
      - parse_logs
      - aggregate_attempts

    thresholds:
      missing_inputs: stop
      missing_commands: stop
      insufficient_permissions: warn
      max_log_volume_mb: 100
      failed_attempts_per_minute: 5

    analysis:
      - type: failed_login
        condition: "failed_count > 5"
        severity: high
      - type: disabled_user_login
        condition: "login_by_disabled_user == true"
        severity: medium

    outputs:
      format: json
      path: /var/lib/hl-monitor/artifacts/ssh_login/
      forward_to: siem
      archive_signed: true

  fim_monitor:
    name: "File Integrity Monitoring"
    description: "Detect unauthorized changes to critical files."
    
    task_type: cron
    schedule: "0 */6 * * *"  # run every 6 hours
    continuous: false

    dependencies:
      inputs:
        - /etc/aide.conf
        - /usr/bin/
        - /etc/
      commands:
        - aide
      libraries: []
      permissions: root
      runtime:
        disk_min_mb: 500

    steps:
      - run_aide_check
      - compress_results
      - sign_results

    thresholds:
      aide_check_fail: stop
      changed_files_limit: 1000

    analysis:
      - type: file_change
        condition: "changed_files_count > 0"
        severity: high

    outputs:
      format: json
      path: /var/lib/hl-monitor/artifacts/fim/
      forward_to: siem
      archive_signed: true

  process_network_snapshot:
    name: "Process & Network Snapshot"
    description: "Capture running processes and network connections."
    
    task_type: daemon
    continuous: true         # run continuously, e.g., every 5 minutes internally
    interval_seconds: 300    # only for daemon tasks

    dependencies:
      inputs: []
      commands:
        - ps
        - ss
        - lsof
      libraries:
        - psutil
      permissions: root
      runtime:
        disk_min_mb: 50

    steps:
      - collect_processes
      - collect_network
      - compress_snapshot

    thresholds:
      missing_commands: stop
      snapshot_size_mb: 50

    analysis:
      - type: unexpected_process
        condition: "process not in baseline"
        severity: medium
      - type: unexpected_connection
        condition: "port not in baseline"
        severity: medium

    outputs:
      format: json
      path: /var/lib/hl-monitor/artifacts/process_network/
      forward_to: siem
      archive_signed: true
